### ISSUE TITLE
Make an Resource Controller

### ISSUE THREAD

**Issue by natanfelles** [lonnieezell/vulcan#13]
With all methods of [resource-routes](https://bcit-ci.github.io/CodeIgniter4/general/routing.html#resource-routes).

**Comment by natanfelles** [comment]
If to include it, add a `ResourceController` or update the `CRUDController`?

**Comment by lonnieezell** [comment]
I think there's only 1 or 2 methods that are different between the current CRUD controller and a resource controller, right? I would just update the CRUD controller. Heck, I would just turn the current controller generator into a resource controller so we don't duplicate.
