### ISSUE TITLE
Project Abandoned?

### ISSUE THREAD

**Issue by PwrSrg** [lonnieezell/vulcan#24]
So I take it "since it's sure to launch on or before CodeIgniter 4 does" didn't happen.

Is this project abandoned?

**Comment by lonnieezell** [comment]
Not abandoned, I just haven't had the time to get in and fix it quite yet. It's probably 90% of the way to where it should be. 

Would definitely accept contributions to the project!

**Comment by PwrSrg** [comment]
Ok, thanks great news!

I honestly didn't realize this was your repo, and the only commands I saw started were Model and Controller.  I now realize that I was looking at a different branch.

Well hopefully you find time soon, and I look forward to it's final release!

Thanks for all the hard work!
